export const ADD_OBSERVATION_ADDRESS = 'ADD_OBSERVATION_ADDRESS'
export const DELETE_OBSERVATION_ADDRESS = 'DELETE_OBSERVATION_ADDRESS'

export const LOAD_BALANCES = 'LOAD_BALANCES'
export const LOAD_TRANSACTIONS = 'LOAD_TRANSACTIONS'

export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'