export const ADD_OBSERVATION_ADDRESS = 'ADD_OBSERVATION_ADDRESS'
export const DELETE_OBSERVATION_ADDRESS = 'DELETE_OBSERVATION_ADDRESS'

export const LOAD_ADDRESSES_BALANCES = 'LOAD_ADDRESSES_BALANCES'

export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'